# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecfa2 <- function(u, Sigma, domain, person, item, eta, new_a, new_b) {
    .Call(`_VEMIRT_ecfa2`, u, Sigma, domain, person, item, eta, new_a, new_b)
}

acfa2 <- function(u, indic, person, item, domain, eta, new_b, SIGMA, MU, new_a1) {
    .Call(`_VEMIRT_acfa2`, u, indic, person, item, domain, eta, new_b, SIGMA, MU, new_a1)
}

lb2pl <- function(u, xi, sig, new_a, new_b, SIGMA, MU) {
    .Call(`_VEMIRT_lb2pl`, u, xi, sig, new_a, new_b, SIGMA, MU)
}

ecfa3pl <- function(u, Sigma, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1) {
    .Call(`_VEMIRT_ecfa3pl`, u, Sigma, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1)
}

s3pl <- function(item, id_1, s, eta, new_a, s_num, new_b, u, SIGMA, MU, xi) {
    .Call(`_VEMIRT_s3pl`, item, id_1, s, eta, new_a, s_num, new_b, u, SIGMA, MU, xi)
}

eta3pl <- function(item, id_1, ea, xi) {
    .Call(`_VEMIRT_eta3pl`, item, id_1, ea, xi)
}

b3pl <- function(item, id_1, new_s, eta, u, new_a, dec_st, MU, prev_b_num, prev_b_denom, mu_b, sigma2_b) {
    .Call(`_VEMIRT_b3pl`, item, id_1, new_s, eta, u, new_a, dec_st, MU, prev_b_num, prev_b_denom, mu_b, sigma2_b)
}

acfa3 <- function(u, indic, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st) {
    .Call(`_VEMIRT_acfa3`, u, indic, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st)
}

lb3pl <- function(u, xi, s, id_1, new_a, new_c, sig, new_b, SIGMA, MU, Alpha, Beta, mu_b, sigma2_b) {
    .Call(`_VEMIRT_lb3pl`, u, xi, s, id_1, new_a, new_c, sig, new_b, SIGMA, MU, Alpha, Beta, mu_b, sigma2_b)
}

eefa2 <- function(u, domain, person, item, eta, new_a, new_b) {
    .Call(`_VEMIRT_eefa2`, u, domain, person, item, eta, new_a, new_b)
}

aefa2 <- function(u, domain, person, item, eta, new_b, SIGMA, MU) {
    .Call(`_VEMIRT_aefa2`, u, domain, person, item, eta, new_b, SIGMA, MU)
}

paal2pl <- function(u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU, weights) {
    .Call(`_VEMIRT_paal2pl`, u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU, weights)
}

paalc22pl <- function(u, a, indic, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU, weights) {
    .Call(`_VEMIRT_paalc22pl`, u, a, indic, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU, weights)
}

paalc22pl1 <- function(u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc, weights) {
    .Call(`_VEMIRT_paalc22pl1`, u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc, weights)
}

nalc12pl <- function(u, indic, nopenalty_col, person, eta, new_b, SIGMA, MU) {
    .Call(`_VEMIRT_nalc12pl`, u, indic, nopenalty_col, person, eta, new_b, SIGMA, MU)
}

palc12pl <- function(u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU) {
    .Call(`_VEMIRT_palc12pl`, u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU)
}

nalc22pl <- function(u, domain, a, nopenalty_col, lastone, person, eta, new_b, SIGMA, MU) {
    .Call(`_VEMIRT_nalc22pl`, u, domain, a, nopenalty_col, lastone, person, eta, new_b, SIGMA, MU)
}

palc22pl <- function(u, a, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU) {
    .Call(`_VEMIRT_palc22pl`, u, a, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU)
}

palc22pl1 <- function(u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc) {
    .Call(`_VEMIRT_palc22pl1`, u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc)
}

eefa3 <- function(u, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1) {
    .Call(`_VEMIRT_eefa3`, u, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1)
}

aefa3 <- function(u, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st) {
    .Call(`_VEMIRT_aefa3`, u, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st)
}

paal3pl <- function(u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights, sdf) {
    .Call(`_VEMIRT_paal3pl`, u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights, sdf)
}

paalc23pl <- function(u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights) {
    .Call(`_VEMIRT_paalc23pl`, u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights)
}

paalc23pl1 <- function(u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22, weights) {
    .Call(`_VEMIRT_paalc23pl1`, u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22, weights)
}

nalc13pl <- function(u, indic, nopenalty_col, eta, s, new_b, SIGMA, MU, a, id_1, prev_a_num, prev_a_denom, dec_st) {
    .Call(`_VEMIRT_nalc13pl`, u, indic, nopenalty_col, eta, s, new_b, SIGMA, MU, a, id_1, prev_a_num, prev_a_denom, dec_st)
}

palc13pl <- function(u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, sdf) {
    .Call(`_VEMIRT_palc13pl`, u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, sdf)
}

nalc23pl <- function(u, domain, item, a, nopenalty_col, lastone, s, eta, new_b, SIGMA, MU, id_1, prev_a_num, prev_a_denom, dec_st) {
    .Call(`_VEMIRT_nalc23pl`, u, domain, item, a, nopenalty_col, lastone, s, eta, new_b, SIGMA, MU, id_1, prev_a_num, prev_a_denom, dec_st)
}

palc23pl <- function(u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2) {
    .Call(`_VEMIRT_palc23pl`, u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2)
}

palc23pl1 <- function(u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22) {
    .Call(`_VEMIRT_palc23pl1`, u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22)
}

